```{r}
library(doParallel)
library(R2jags)
library(random)
library(reshape2)
library(ggplot2)
library(knitr)
require(gridExtra)
source("HPD.R")

```


```{r cond likelihood}
cond.likelihood.model = function() {
  for (j in 1:J) {
    CaseCon[j] ~ dbern(theta[j])
    logit(theta[j]) <-  mu.p53  }
  
  C<-1000
  for (k in 1:n.discovery){
    #zeroes trick for MLE~cond prob
    tau[k]<- pow(SE[k], -2)
    L[k]<- dnorm(MLE[k],mu.p53, tau[k])/(pnorm(-q*SE, mu.p53, tau[k]) +
                                           1-pnorm(q*SE, mu.p53, tau[k]))
    phi[k]<- -log(L[k])+C
    zeroes[k]~dpois(phi[k])
  }
  
  mu.p53 ~ dnorm(0,.1)
  phi.p53 ~ dgamma(1, .05)
  
  pind ~ dbeta(.5,.5)
}

get.cond.likelihood.data<- function(data, p = 0.00325){
  freq = glm(CaseCon ~ factor(site), data=data,family=binomial, x=T)
  #get "discovery" with smallest p value (that is significant)
  coefs = coef(summary(freq))
  discovery.site = which.min(coefs[,4])
  if(coefs[discovery.site,4]>p){
    return(NULL)
  }
  
  MLE = coefs[discovery.site,1]
  SE = coefs[discovery.site,2]
  #make new data for model
  exclude <- which(data$site==discovery.site)
  newdata = list(MLE=MLE, SE=SE, n.discovery= 1, zeroes= 0, 
                 CaseCon= data$CaseCon[-exclude], 
                 site= data$site[-exclude], n.sites = data$n.sites-1,
                 q=qnorm(1-p/2))
  newdata$J<- length(newdata$CaseCon)
  return(newdata)
  
}
```

```{r jags models}
ones.cauchy.model= function() {
  for (j in 1:J) {
    CaseCon[j] ~ dbern(theta[j])
    logit(theta[j]) <-  beta.p53[site[j]]  }
  
  for (l in 1:n.sites) {
    beta.p53.1[l] ~ dnorm(mu.p53, phi.p53)
    beta.p53[l] <- beta.p53.1[l]*(mu.p53.notzero)
  }
  #ones trick
  C<-1e6
  epsilon<-0.01
  tau<- pow(epsilon,-2)
  mu.p53.notzero<- step(temp)
  temp<-dt(mu.p53,0,1, 1)-dnorm(mu.p53,0,tau) 
  #cauchy is same as t with df=1
  L<-(dnorm(mu.p53,0,tau)*(1-pind))+(dt(mu.p53,0,1,1)*pind)
  p <- L/ C
  one~ dbern(p)
  mu.p53 ~ dunif(-10,10) 
  phi.p53 ~ dgamma(1, .05)
  sigma.p53 <- pow(phi.p53, -.5)
  pind ~ dbeta(.5,.5)
}

ones.normal.model= function() {
  for (j in 1:J) {
    CaseCon[j] ~ dbern(theta[j])
    logit(theta[j]) <-  beta.p53[site[j]]  }
  
  for (l in 1:n.sites) {
    beta.p53.1[l] ~ dnorm(mu.p53, phi.p53)
    beta.p53[l] <- beta.p53.1[l]*(mu.p53.notzero)
  }
  #ones trick
  C<-1e6
  epsilon<-0.01
  tau<- pow(epsilon,-2)
  mu.p53.notzero<- step(temp)
  temp<-dnorm(mu.p53,0,1)-dnorm(mu.p53,0,tau) 
  L<-(dnorm(mu.p53,0,tau)*(1-pind))+(dnorm(mu.p53,0,1)*pind)
  p <- L/ C
  one ~ dbern(p)
  mu.p53 ~ dunif(-10,10) 
  phi.p53 ~ dgamma(1, .05)
  sigma.p53 <- pow(phi.p53, -.5)
  pind ~ dbeta(.5,.5)
}

latent.normal.model= function() {
  for (j in 1:J) {
    CaseCon[j] ~ dbern(theta[j])
    logit(theta[j]) <-  beta.p53[site[j]]  }
  
  for (l in 1:n.sites) {
    beta.p53.1[l] ~ dnorm(mu.p53, phi.p53)
    beta.p53[l] <- beta.p53.1[l]*(mu.p53.notzero)
  }
  
  mu.p53<- mu1.p53*mu.p53.notzero
  mu1.p53 ~ dnorm(0,1)
  phi.p53 ~ dgamma(1, .05)
  sigma.p53 <- pow(phi.p53, -.5)
  
  mu.p53.notzero~dbern(pind)
  pind ~ dbeta(.5,.5)
}

latent.cauchy.model= function() {
  for (j in 1:J) {
    CaseCon[j] ~ dbern(theta[j])
    logit(theta[j]) <-  beta.p53[site[j]]  }
  
  for (l in 1:n.sites) {
    beta.p53.1[l] ~ dnorm(mu.p53, phi.p53)
    beta.p53[l] <- beta.p53.1[l]*(mu.p53.notzero)
  }
  
  mu.p53<- mu1.p53*mu.p53.notzero
  mu1.p53 ~ dt(0,1, 1)
  phi.p53 ~ dgamma(1, .05)
  sigma.p53 <- pow(phi.p53, -.5)
  
  mu.p53.notzero~dbern(pind)
  pind ~ dbeta(.5,.5)
}

fixed.model = function() {
  for (j in 1:J) {
    CaseCon[j] ~ dbern(theta[j])
    logit(theta[j]) <-  mu.p53  
  }
  mu.p53<- mu1.p53*mu.p53.notzero
  mu1.p53 ~ dnorm(0,.1)
  phi.p53 ~ dgamma(1, .05)
  mu.p53.notzero~dbern(pind)
  pind ~ dbeta(.5,.5)
}

#p53.fulljags1.2.l1.cauchy = jags(data=onesdata, ####this
#                    inits=NULL, parameters.to.save =c("pind", 
#"mu.p53", "phi.p53","mu.p53.notzero","temp"),
#                    model = cauchyprior)
```


```{r sampling}
#true mu fixed, smaller variance to make sure it is above 0 (especially since it's learned anyway)

sample<- function(assoc, mu, sd, observations = 1000, n.sites=7){ #assoc is H
  beta.p53 = rnorm(n.sites,mu,sd)*assoc 
  Y <-site <- rep(NA, observations*n.sites)
  for(i in 1:n.sites){
    Y[((i-1)*observations+1):(i*observations)]<-rbinom(observations, 1, exp(beta.p53[i])/(1+exp(beta.p53[i])))
    site[((i-1)*observations+1):(i*observations)]<- rep(i, observations)
  }
  return(list(beta.p53=beta.p53, simdata = list(CaseCon=Y, site=site,  J=n.sites*observations ,n.sites=n.sites, one=1)))
}

```


```{r run fn}
run.all<- function(assoc,mu, sd, inits){
  cond.data = NULL;count=0
  while(is.null(cond.data) & count<1000){
    data <- sample(assoc, mu, sd)
    cond.data<-get.cond.likelihood.data(data$simdata)
    count=count+1
  }
  #run jags
  ones.cauchy <- jags(data=data$simdata, inits=inits, 
                      parameters.to.save =c("pind", "mu.p53", "phi.p53","mu.p53.notzero"),
                      model = ones.cauchy.model)
  ones.normal <- jags(data=data$simdata, inits=inits,
                      parameters.to.save =c("pind", "mu.p53", "phi.p53","mu.p53.notzero"),
                      model = ones.normal.model)
  latent.normal <- jags(data=data$simdata, inits=inits,
                        parameters.to.save =c("pind", "mu.p53", "phi.p53","mu.p53.notzero"),
                        model = latent.normal.model)
  latent.cauchy <- jags(data=data$simdata, inits=inits,
                        parameters.to.save =c("pind", "mu.p53", "phi.p53","mu.p53.notzero"),
                        model = latent.cauchy.model)
  cond.likelihood<-NULL
  if(!is.null(cond.data)){
    cond.likelihood <- jags(data=cond.data ,inits=inits,
                            parameters.to.save =c("pind", "mu.p53", "phi.p53"), 
                            model = cond.likelihood.model)
  }
  
  fixed <- jags(data=data$simdata, inits=inits, 
                parameters.to.save =c("pind", "mu.p53", "phi.p53","mu.p53.notzero"), 
                model = fixed.model)
  
  return(list(ones.cauchy = ones.cauchy, ones.normal=ones.normal,
              latent.normal = latent.normal,latent.cauchy = latent.cauchy,
              cond.likelihood = cond.likelihood,fixed = fixed, beta.p53 = data$beta.p53))
}

```


```{r parallel}
# stopCluster(cl)
cl = makeCluster(8)
registerDoParallel(cl)

# inits= list(mu.p53 = 0, mu.p53.notzero=0, phi.p53=1)
# inits$.RNG.name = "lecuyer::RngStream"
# inits$.RNG.seed = randomNumbers(n=1, min=1, max=1e+06, col=1)

mu=0.203;sd= 0.05831085 #from glmer estimates using all data
assoc<-c(0,1,1,1,1)
muvec<-c(0,mu,mu,mu,mu)
sdvec<-c(1,.5*sd,sd,2*sd,4*sd)

I = 100 #getDoParWorkers()*10
#I=1

system.time({
  allsim<- foreach(j = 1:5) %:%
    foreach ( i = 1:I, .inorder=FALSE, .packages = c("R2jags"))  %dopar% {
      return(run.all(assoc[j],muvec[j],sdvec[j], NULL))
    }
})
save.image()

```

```{r run cl}
run.cl<- function(assoc,mu, sd, inits, p){
  cond.data = NULL;count=0
  while(is.null(cond.data) & count<1000){
    data <- sample(assoc, mu, sd)
    cond.data<-get.cond.likelihood.data(data$simdata, p)
    count=count+1
  }
  if(!is.null(cond.data)){
    cond.likelihood <- jags(data=cond.data ,inits=inits,
                            parameters.to.save =c("pind", "mu.p53", "phi.p53"), 
                            model = cond.likelihood.model)
  }
  return(cond.likelihood)
}

```

```{r parallel cl}
cl = makeCluster(8)
registerDoParallel(cl)
pvals=c(.05,.01,.005,.001, 1e-7)
I=100
system.time({
  cl.sim<- foreach(j = 1:length(pvals)) %:%
    foreach ( i = 1:I, .inorder=FALSE, .packages = c("R2jags"))  %dopar% {
      return(run.cl(1,mu,sd, NULL,pvals[j]))
    }
})
save.image()

cl = makeCluster(8)
registerDoParallel(cl)
pvals=c(.05,.01,.005,.001, 1e-7)
I=100
system.time({
  cl.sim2<- foreach(j = 1:length(pvals)) %:%
    foreach ( i = 1:I, .inorder=FALSE, .packages = c("R2jags"))  %dopar% {
      return(run.cl(1,mu,sd*4, NULL,pvals[j]))
    }
})
save.image()
```

```{r summary stats}
getstatsitems<-c("hasmu","haszero","mean","median",
                 "ismultimodal", "intervallength","probzero",
                 "hassd","sdmean","sdmedian","sdintlen",
                 "haspind","pindmean","pindmedian","pindintlen")

modelnames<- c("Cauchy-Ones Trick","Normal-Ones Trick",
               "Normal-Latent","Cauchy-Latent",
               "Cond Likelihood", "Fixed Effect")
getstatsloop<-function(simlist,mu,sd,pind, e=.03){
  I<-length(simlist)
  vec<-sapply(simlist, function(outputlist) sapply(outputlist[-7],getstats,mu,sd,pind, e))
  return(array(data=vec,dim= c(length(getstatsitems),length(modelnames),I), dimnames=list(getstatsitems,modelnames,seq(1:I))))
}

getstats<-function(jagsoutput, mu, sd, pind, e = .03){
  mu.samples<- jagsoutput$BUGSoutput$sims.list$mu.p53
  cred<-HPDM(mu.samples,e)
  upper<- cred[2]
  lower<- cred[1]
  if(length(cred)>2){
    #assume 2 modes max
    upper <- c(upper,cred[4])
    lower <- c(lower,cred[3])
  }
  
  sd.samples <- (jagsoutput$BUGSoutput$sims.list$phi.p53)^-.5
  sd.cred<- HPDM(sd.samples)
  pind.samples<- jagsoutput$BUGSoutput$sims.list$pind
  pind.cred<- HPDM(pind.samples)
  return(c(hasmu = any(upper>=mu&lower<=mu), 
           haszero = any(upper>=-e&lower<=e), 
           mean = mean(mu.samples),
           median = median(mu.samples),
           ismultimodal=length(cred)>2,
           intervallength = sum(upper-lower),
           probzero = sum(abs(mu.samples)<=e)/length(mu.samples),
           hassd= sd.cred[2]>=sd&sd.cred[1]<=sd,
           sdmean= mean(sd.samples),
           sdmedian= median(sd.samples),
           sdintlen=sd.cred[2]-sd.cred[1],
           haspind=pind.cred[2]>=pind&pind.cred[1]<=pind,
           pindmean =mean(pind.samples),
           pindmedian=median(pind.samples),
           pindintlen=pind.cred[2]-pind.cred[1]
           
  ))
}

```


```{r get stats}
sim.0<-getstatsloop(allsim[[1]],0, 1, 0) #13 modes?
sim.half<-getstatsloop(allsim[[2]],mu, sd*.5, 1)
sim.1<-getstatsloop(allsim[[3]],mu, sd, 1)
sim.2<-getstatsloop(allsim[[4]],mu,sd*2,1)
sim.4<-getstatsloop(allsim.5[[1]],mu,sd*4,1)

```





```{r plotting fn}
make_simlist<-function(sim){
  OC<-t(sim[,1,])
  ON<-t(sim[,2,])
  LN<-t(sim[,3,])
  LC<-t(sim[,4,])
  CL<-t(sim[,5,])
  FE<-t(sim[,6,])
  #sapply(list(OC,ON,LN,LC,CL,FE), function(X) colnames(X)<- getstatsitems)
  return(list(OC,ON,LN,LC,CL,FE))
}

make_plots<-function(simlist, mu, modelnames){

  mean.sqerr<- data.frame(sapply(simlist, function(x) abs(x[,3]-mu)))
  colnames(mean.sqerr)<-modelnames
  mean.sqerr$estimator <- rep("mean",dim(mean.sqerr)[1])
  
  median.sqerr<- data.frame(sapply(simlist, function(x) abs(x[,4]-mu)))
  colnames(median.sqerr)<-modelnames
  median.sqerr$estimator <- rep("median",dim(median.sqerr)[1])
  
  sqerr<- rbind(mean.sqerr,median.sqerr)
  
  #mse
  plot1<- (ggplot(data = melt(sqerr), aes(x=variable, y=value,color=estimator)) +
             geom_boxplot()+labs(x= "Posterior Mean", y="Squared Error", 
                                 title= "Squared Error Distribution with Mean"))
  
  #bar plots for coverage, times it's right
  coverage<- data.frame(sapply(simlist, function(x) x[,1]))
  colnames(coverage)<-modelnames
  
  containszero<- data.frame(sapply(simlist, function(x) x[,2]))
  both<- coverage*containszero
  coverage[coverage==1]<-2
  coverage[containszero==1]<-1
  coverage[both==1]<-3
  coverage1<-melt(coverage)
  levelnames<-c("Neither", "Only Zero","Only Mu","Both")
  coverage1$value<-factor(levelnames[coverage1$value+1])
  plot2<-( ggplot(data = coverage1, 
                  aes(x=variable,fill=value,y=rep(1, length(variable))))+
             geom_bar(stat="identity")+labs(x= "Model", y="Coverage", 
                                            title= "Coverage"))
  print(kable(table(coverage1)/100))
  
  disjoint<- data.frame(sapply(simlist, function(x) x[,5]))
  d0 = (containszero==0)*(disjoint)
  colnames(d0) = modelnames
  print(kable(table(melt(d0))))
  #interval length
  intlen<- data.frame(sapply(simlist, function(x) x[,6]))
  colnames(intlen)<-modelnames
  
  plot3<-(ggplot(data = melt(intlen), aes(x=variable, y=value)) +
            geom_boxplot()+labs(x= "Model", y="Credible Interval Length", 
                                title= "Intervals"))
  #prob of zero
  p0<- data.frame(sapply(simlist, function(x) x[,7]))
  colnames(p0)<-modelnames
  
  plot4 <- (ggplot(data = melt(p0), aes(x=variable, y=value)) +
              geom_boxplot()+labs(x= "Model", y="probability of mu=0", 
                                  title= "Posterior Probability of Null (H=0)"))
  
  grid.arrange(plot1, plot2, plot3,plot4 ,ncol=2)
}

```


```{r}
make_plots(make_simlist(sim.0), 0,modelnames)
make_plots(make_simlist(sim.half), mu,modelnames)
make_plots(make_simlist(sim.1), mu,modelnames)
make_plots(make_simlist(sim.2), mu,modelnames)
make_plots(make_simlist(sim.4), mu,modelnames)

```

```{r cl analysis}
sim.cl.1<-sapply(cl.sim[[1]], getstats,mu,sd,1)
sim.cl.2<-sapply(cl.sim[[2]], getstats,mu,sd,1)
sim.cl.3<-sapply(cl.sim[[3]], getstats,mu,sd,1)
sim.cl.4<-sapply(cl.sim[[4]], getstats,mu,sd,1)
sim.cl.5<-sapply(cl.sim[[5]], getstats,mu,sd,1)
make_plots(list(t(sim.cl.1), t(sim.cl.2), t(sim.cl.3),t(sim.cl.4),t(sim.cl.5)), mu, pvals)

```





