# Supplementary Material

## JAGS Models


```{r, echo = TRUE, eval=FALSE}
cond.likelihood.model = function() {
  for (j in 1:J) {
    CaseCon[j] ~ dbern(theta[j])
    logit(theta[j]) <-  mu.p53  }
  
  C<-1000
  for (k in 1:n.discovery){
    #zeroes trick for MLE~cond prob
    tau[k]<- pow(SE[k], -2)
    L[k]<- dnorm(MLE[k],mu.p53, tau[k])/(pnorm(-q*SE, mu.p53, tau[k]) +
                                           1-pnorm(q*SE, mu.p53, tau[k]))
    phi[k]<- -log(L[k])+C
    zeroes[k]~dpois(phi[k])
  }
  
  mu.p53 ~ dnorm(0,.1)
  
}

cond.likelihood.re.model = function() {
  for (j in 1:J) {
    CaseCon[j] ~ dbern(theta[j])
    logit(theta[j]) <-  beta.p53[site[j]]  }
  
  C<-1000
  for (k in 1:n.discovery){
    #zeroes trick for MLE~cond prob
    tau[k]<- pow(SE[k], -2)
    L[k]<- dnorm(MLE[k],beta.p53[discovery.sites[k]], tau[k])/
      (pnorm(-q*SE[k], beta.p53[discovery.sites[k]], tau[k]) +
         1-pnorm(q*SE[k], beta.p53[discovery.sites[k]], tau[k]))
    phi[k]<- -log(L[k])+C
    zeroes[k]~dpois(phi[k])
  }
  for (i in 1:n.sites){ #total sites
    beta.p53[i] ~dnorm(mu.p53,phi.p53)
  }
  
  mu.p53 ~ dnorm(0,.1)
  # phi.p53 ~ dgamma(1, .05)
  # sigma.p53 <- pow(phi.p53, -.5)
  phi.p53 <- pow(sigma.p53, -2)
  sigma.p53 ~ dt(0,1,1)%_%T(0,)
}

ones.cauchy.model= function() {
  for (j in 1:J) {
    CaseCon[j] ~ dbern(theta[j])
    logit(theta[j]) <-  beta.p53[site[j]]  }
  
  for (l in 1:n.sites) {
    beta.p53.1[l] ~ dnorm(mu.p53, phi.p53)
    beta.p53[l] <- beta.p53.1[l]*(mu.p53.notzero)
  }
  #ones trick
  C<-1e6
  epsilon<-0.01
  tau<- pow(epsilon,-2)
  mu.p53.notzero<- step(temp)
  temp<-dt(mu.p53,0,1, 1)-dnorm(mu.p53,0,tau) 
  #cauchy is same as t with df=1
  L<-(dnorm(mu.p53,0,tau)*(1-pind))+(dt(mu.p53,0,1,1)*pind)
  p <- L/ C
  one~ dbern(p)
  mu.p53 ~ dunif(-10,10) 
  # phi.p53 ~ dgamma(1, .05)
  # sigma.p53 <- pow(phi.p53, -.5)
  phi.p53 <- pow(sigma.p53, -2)
  sigma.p53 ~ dt(0,1,1)%_%T(0,)
  pind ~ dbeta(.5,.5)
}

ones.normal.model= function() {
  for (j in 1:J) {
    CaseCon[j] ~ dbern(theta[j])
    logit(theta[j]) <-  beta.p53[site[j]]  }
  
  for (l in 1:n.sites) {
    beta.p53.1[l] ~ dnorm(mu.p53, phi.p53)
    beta.p53[l] <- beta.p53.1[l]*(mu.p53.notzero)
  }
  #ones trick
  C<-1e6
  epsilon<-0.01
  tau<- pow(epsilon,-2)
  mu.p53.notzero<- step(temp)
  temp<-dnorm(mu.p53,0,1)-dnorm(mu.p53,0,tau) 
  L<-(dnorm(mu.p53,0,tau)*(1-pind))+(dnorm(mu.p53,0,1)*pind)
  p <- L/ C
  one ~ dbern(p)
  mu.p53 ~ dunif(-10,10) 
  # phi.p53 ~ dgamma(1, .05)
  # sigma.p53 <- pow(phi.p53, -.5)
  phi.p53 <- pow(sigma.p53, -2)
  sigma.p53 ~ dt(0,1,1)%_%T(0,)
  pind ~ dbeta(.5,.5)
}

latent.normal.model= function() {
  for (j in 1:J) {
    CaseCon[j] ~ dbern(theta[j])
    logit(theta[j]) <-  beta.p53[site[j]]  }
  
  for (l in 1:n.sites) {
    beta.p53.1[l] ~ dnorm(mu.p53, phi.p53)
    beta.p53[l] <- beta.p53.1[l]*(mu.p53.notzero)
  }
  
  mu.p53<- mu1.p53*mu.p53.notzero
  mu1.p53 ~ dnorm(0,1)
  # phi.p53 ~ dgamma(1, .05)
  # sigma.p53 <- pow(phi.p53, -.5)
  phi.p53 <- pow(sigma.p53, -2)
  sigma.p53 ~ dt(0,1,1)%_%T(0,)
  mu.p53.notzero~dbern(pind)
  pind ~ dbeta(.5,.5)
}

latent.cauchy.model= function() {
  for (j in 1:J) {
    CaseCon[j] ~ dbern(theta[j])
    logit(theta[j]) <-  beta.p53[site[j]]  }
  
  for (l in 1:n.sites) {
    beta.p53.1[l] ~ dnorm(mu.p53, phi.p53)
    beta.p53[l] <- beta.p53.1[l]*(mu.p53.notzero)
  }
  
  mu.p53<- mu1.p53*mu.p53.notzero
  mu1.p53 ~ dt(0,1, 1)
  # phi.p53 ~ dgamma(1, .05)
  # sigma.p53 <- pow(phi.p53, -.5) #half cauchy, uniform to 1 or to 5, take a guess on sd
  phi.p53 <- pow(sigma.p53, -2)
  sigma.p53 ~ dt(0,1,1)%_%T(0,)
  mu.p53.notzero~dbern(pind)
  pind ~ dbeta(.5,.5)
}

fixed.model = function() {
  for (j in 1:J) {
    CaseCon[j] ~ dbern(theta[j])
    logit(theta[j]) <-  mu.p53  
  }
  mu.p53<- mu1.p53*mu.p53.notzero
  mu1.p53 ~ dnorm(0,.1)
  mu.p53.notzero~dbern(pind)
  pind ~ dbeta(.5,.5)
}

original.model = function() {
  for (j in 1:J) {
    CaseCon[j] ~ dbern(theta[j])
    logit(theta[j]) <-  beta.p53[site[j]]  }
  
  for (l in 1:n.sites) {
    beta.p53[l] ~ dnorm(mu.p53, phi.p53)
  }
  
  mu.p53 ~ dnorm(0,1)
  phi.p53 ~ dgamma(1, .05)
  sigma.p53 <- pow(phi.p53, -.5)
}

bf.model = function() {
  for (j in 1:J) {
    CaseCon[j] ~ dbern(theta[j])
    logit(theta[j]) <-  beta.p53[site[j]] }
  
  for (l in 1:n.sites) {
    beta.p53.1[l] ~ dnorm(mu.p53, phi.p53)
    beta.p53[l] <- beta.p53.1[l]*(mu.p53.notzero)
  }
  
  mu.p53<- mu1.p53*mu.p53.notzero
  mu1.p53 ~ dt(0,1,1)
  phi.p53 <- pow(sigma.p53, -2)
  sigma.p53 ~ dt(0,1,1)%_%T(0,)
  
  mu.p53.notzero~dbern(pind)
  prior.odds<- (1-prior.pind)/prior.pind
  BF<- 1/(-exp(1)*p*log(p)) #eplogp is BF h0/h1
  pind<-prior.odds*BF/(1+prior.odds*BF)
  prior.pind ~ dbeta(.9,.9)
}

```



## Joint Analysis of TP53 SNPs


```{r include=FALSE}
knitr::opts_chunk$set(cache = TRUE)
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(echo = FALSE)


```

```{r all together,eval = FALSE,echo = FALSE}
getalldata<- function(iter=5000, drop.sites= NULL){
  
  #more iterations, coda traceplots, maybe look at the prior still- cauchy prior? ideally would do joint update (check if model is reducible-> chain gets stuck)-> maube google this bc jags probably 
  #
  
  load("tp53.Rdata")
  
  if(!is.null(drop.sites)) {
    use = !(tp53epi.wsi$site %in% drop.sites)
  } else {
    use = rep(TRUE, nrow(tp53epi.wsi))
  }
  
  names = colnames(tp53geno.wsi)
  maxsite = 0
  CaseCon<- site<-  BC <-  Age <- SNP <- p53<-NULL
  for(i in 1:length(names)){
    snp.name<- names[i]
    p53.snp = tp53geno.wsi[use, snp.name]
    tp53epi.wsi = tp53epi.wsi[use,]
    
    missing.geno = is.na(p53.snp)
    site.names = levels(factor(tp53epi.wsi[!missing.geno,"site"]))
    
    CaseCon<- c(CaseCon, tp53epi.wsi$casecon[!missing.geno])
    site<-c(site, as.numeric(factor(tp53epi.wsi$site[!missing.geno]))+
              maxsite)
    maxsite <-max(site)
    BC <- c(BC, as.numeric(tp53epi.wsi$prev.BC[!missing.geno]))
    Age <- c(Age, tp53epi.wsi$refage[!missing.geno])
    SNP <-c(SNP,  rep(i, length(unique(tp53epi.wsi$site[!missing.geno]))))
    p53<-c(p53, p53.snp[!missing.geno])
  }
  p53.data<- list(CaseCon = CaseCon,site=site,BC = BC,Age = Age,SNP = SNP,p53 = p53)
  J = length(p53.data$CaseCon)
  n.sites = length(unique(p53.data$site))
  p53.data$J = J
  p53.data$n.sites = n.sites
  p53.data$n.snp = length(unique(p53.data$SNP))
  p53.data$snps = names
  return(p53.data)
}

p53.newmodel.all = function() {
  for (j in 1:J) {
    CaseCon[j] ~ dbern(theta[j])
    logit(theta[j]) <- beta.site[site[j]] + beta.p53[site[j]]*p53[j] +
      beta.Age[site[j]]*Age[j] + beta.BC[SNP[site[j]]]*BC[j]    }
  
  for (l in 1:n.sites) {
    beta.site[l] ~ dnorm(mu.site[SNP[l]], phi.site[SNP[l]])
    beta.p53.1[l] ~ dnorm(mu.p53[SNP[l]], phi.p53[SNP[l]])
    beta.p53[l] <- beta.p53.1[l]*assoc[SNP[l]]
    beta.Age[l] ~ dnorm(mu.Age[SNP[l]], phi.Age[SNP[l]])
  }
  
  for (k in 1:n.snp){
    beta.BC[k] ~ dnorm(0, .1)
    mu.site[k] ~ dnorm(0, .1)
    phi.site[k] ~ dgamma(1,.05)
    sigma.site[k] <- pow(phi.site[k], -.5)
    
    #E[prec] 20
    #(based on range .5 to 2 for OR => range = 1.4 = 6 sigma  sigma = 1.4/6 ~= .2 
    mu.p53[k]<- mu1.p53[k]*assoc[k]
    mu1.p53[k] ~ dt(0,.1, 1)
    phi.p53[k] <- pow(sigma.p53[k], -2)
    sigma.p53[k] ~ dt(0,1,1)%_%T(0,)
    
    mu.Age[k] ~ dnorm(0, .1)
    phi.Age[k] ~ dgamma(1, .05)
    sigma.Age[k]  <- pow(phi.Age[k], -.5)
    
    assoc[k] ~ dbern(pind[k]) 
    pind[k] ~ dbeta(.5,.5)
  }
  
}

p53.alldata<- getalldata()
p53.simnew.all = jags(data=p53.alldata, inits=NULL, parameters.to.save =parameters, model = p53.newmodel.all)
MU.ALL<-as.data.frame(p53.simnew.all$BUGSoutput$sims.matrix)%>%select( starts_with("mu.p53"))
snps<- p53.alldata$snps
save(MU.ALL,snps, file="joint_results.RData")
```


```{r, eval=TRUE}
load("joint_results.RData")
source("HPD.R")

mu.all.summary<-apply(MU.ALL,2,function(m){
  if(length(HPDM(m))==4){
    return(c(median(m) ,HPDM(m)))
  } 
  else{
    return(c(median(m) ,HPDM(m), NA, NA))
  }
  
})
mu.all.summary<-t(mu.all.summary)
  est<-round(mu.all.summary[,1], 3)
  CI<-apply(round(mu.all.summary, 3),1, formatCI)
  ret<-cbind(est,CI)
  colnames(ret)<- c("estimate"," 95% CI")
  rownames(ret)<- snps
  

kable(ret, caption="Joint Analysis Estimates of $\\mu_{p53}$")
```



